config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :blogs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    Blog.create(blog_params)
    if @blog.save
      redirect_to blogs_path, notice: "ブログを作成しました！"
    else
      render :new
    end
  end

  def show
    @blog = Blog.find(params[:id])
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/index.html.erb
<h1>blogs</h1>

<table>
  <tr>
    <th>タイトル</th>
    <th>内容</th>
  </tr>

<% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.title %></td>
    <td><%= blog.content %></td>

    <td><%= link_to '詳細を確認する', blog_path(blog.id) %></td>


  </tr>
<% end %>
</table>
<br>
<%= link_to '新しくブログを投稿する', new_blog_path %>

app/views/blogs/new.html.erb
<%= form_with(model: @blog, local: true) do |form| %>
  <div class="blog_title">
    <%= form.label :タイトル %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_content">
    <%= form.label :詳細 %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

app/views/blogs/show.html.erb
<h1>ブログ詳細画面</h1>
<p>タイトル: <%= @blog.title %></p>
<p>内容: <%= @blog.content %></p>
<br>
<%= link_to '前のページに戻る', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Review</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>